config/routes.rb
OpenStax::Connect::Engine.routes.draw do
  match '/auth/openstax/callback', to: 'sessions#omniauth_authenticated' #omniauth route
  get '/auth/openstax', :as => 'openstax_login'

  get 'sessions/new', :as => 'login'
  # See https://github.com/plataformatec/devise/commit/f3385e96abf50e80d2ae282e1fb9bdad87a83d3c
  match 'sessions/destroy', :as => 'logout',
                            :via => OpenStax::Connect.configuration.logout_via

  if OpenStax::Connect.configuration.enable_stubbing?
    namespace :dev do
      resources :users, :only => [] do
        collection do
          get 'login'
          post 'search'
          post 'become'
        end
      end
    end
  end
end


module OpenStax
  module Connect
    hh = Engine.routes.url_helpers

    RouteHelper.register_path(:login, hh.openstax_login_path) { hh.login_dev_users_path }
  end
end

app/models/openstax/connect/user.rb
module OpenStax::Connect
  class User < ActiveRecord::Base

    validates :username, uniqueness: true
    validates :username, presence: true
    validates :openstax_uid, presence: true

    # first and last names are not required

    def name
      (first_name || last_name) ? [first_name, last_name].compact.join(" ") : username
    end

    def casual_name
      first_name || username
    end    

    def is_anonymous?
      is_anonymous == true
    end

    attr_accessor :is_anonymous

    def self.anonymous
      @@anonymous ||= AnonymousUser.new
    end

    class AnonymousUser < User
      before_save { false } 
      def initialize(attributes=nil)
        super
        self.is_anonymous = true
        self.first_name   = 'Guest'
        self.last_name    = 'User'
        self.openstax_uid = nil
      end
    end

  end
end

app/controllers/openstax/connect/application_controller.rb
module OpenStax
  module Connect

    class ApplicationController < ActionController::Base
      include Lev::HandleWith

      # Override current_user to always return an OpenStax::Connect::User
      def current_user
        current_user_manager.connect_current_user
      end

    protected

      def return_url(include_referrer=false)
        referrer = include_referrer ? request.referrer : nil
        # Always clear the session
        session_return_to = session.delete(:return_to)
        params[:return_to] || session_return_to || referrer || main_app.root_url
      end

    end

  end
end

app/controllers/openstax/connect/dev/dev_controller.rb
require_dependency "openstax/connect/application_controller"

module OpenStax
  module Connect
    module Dev
      class DevController < ApplicationController

        before_filter Proc.new{ 
          raise SecurityTransgression if Rails.env.production?
        }
        
      end
    end
  end
end

app/controllers/openstax/connect/dev/users_controller.rb
module OpenStax
  module Connect
    module Dev
      class UsersController < DevController
        
        def login; end

        def search
          handle_with(Dev::UsersSearch,
                      complete: lambda { render 'search' })
        end

        def become
          sign_in(User.find(params[:user_id]))
          redirect_to return_url(true)
        end

      end
    end
  end
end

app/controllers/openstax/connect/sessions_controller.rb
require_dependency "openstax/connect/application_controller"

module OpenStax
  module Connect
    class SessionsController < ApplicationController

      def new
        session[:return_to] ||= request.referrer
        redirect_to RouteHelper.get_path(:login)
      end

      def omniauth_authenticated
        handle_with(SessionsOmniauthAuthenticated,
                    success: lambda {
                      sign_in(@handler_result.outputs[:connect_user_to_sign_in])
                      # referrer is in Accounts, so don't include it
                      redirect_to return_url
                    },
                    failure: lambda {
                      failure
                    })
      end

      def destroy
        sign_out!

        # If we're using the Accounts server, need to sign out of it so can't 
        # log back in automagically
        redirect_to OpenStax::Connect.configuration.enable_stubbing? ?
                      return_url :
                      OpenStax::Utilities.generate_url(
                        OpenStax::Connect.configuration.openstax_accounts_url + "/logout",
                        return_to: return_url
                      )
      end

      def failure
        redirect_to return_url, alert: "Authentication failed, please try again."
      end

    end
  end
end

app/helpers/openstax/connect/application_helper.rb
module OpenStax
  module Connect
    module ApplicationHelper

      def unless_errors(options={}, &block)
        options[:errors] ||= @handler_result.errors
        options[:errors_html_id] ||= OpenStax::Connect.configuration.default_errors_html_id
        options[:errors_partial] ||= OpenStax::Connect.configuration.default_errors_partial
        options[:trigger] ||= OpenStax::Connect.configuration.default_errors_added_trigger

        if options[:errors].any? || flash[:alert]
          "$('##{options[:errors_html_id]}').html('#{ j(render options[:errors_partial], errors: options[:errors]) }').trigger('#{options[:trigger]}');".html_safe
        else
          ("$('##{options[:errors_html_id]}').html('');" + capture(&block)).html_safe
        end
      end

    end
  end
end

app/views/layouts/openstax/connect/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectRails</title>
  <%= stylesheet_link_tag    "openstax/connect/application", :media => "all" %>
  <%= javascript_include_tag "openstax/connect/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/openstax/connect/dev/users/login.html.erb
<div class="openstax-connect development-login">

  <% handler_errors.each do |error| %>
    <%= error.translate %>
  <% end %>

  <%= osu.section_block "Development Login" do %>

    <p>You need to login, but we're not connected to the Accounts server. Search for a user below 
       and click the sign in link next to him or her.</p>

    <%= render 'openstax/connect/users/action_search', action_search_path: search_dev_users_path %>

  <% end %>

</div>

app/views/openstax/connect/dev/users/search.js.erb
<%= render template: 'openstax/connect/users/action_search',
           locals: {
             users: @handler_result.outputs[:users],
             list: OpenStax::Connect::ActionList.new(
                     headings: ['First Name', 'Last Name', 'Username', ''],
                     widths: ['25%', '25%', '25%', '25%'],
                     data_procs:
                       [
                         Proc.new { |user| user.first_name },
                         Proc.new { |user| user.last_name },
                         Proc.new { |user| user.username },
                         Proc.new { |user| 
                          link_to 'Sign in as', 
                                  become_dev_users_path(:user_id => user.id), 
                                  method: :post 
                         }
                       ]
                   )
           }
%>

app/views/openstax/connect/shared/_attention.html.erb
<% handler_errors.each do |error| %>
  <%= error.translate %>
<% end %>

app/views/openstax/connect/users/_action_create_form.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<%# Callers must supply a 'user' local variable %>

<%= form_for target, :method => :post, :remote => true do |f| %>
  <%= f.hidden_field :user_id, :value => user.id %>
  <%= f.submit "Add", :onclick => please_wait_js %>
<% end %>

app/views/openstax/connect/users/_action_dialog.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<div id="user_action_dialog" style="display:none" title="<%= @action_dialog_title %>">
  <div id="user_action_dialog_errors"></div>
  
  <%= render :partial => 'users/action_search', 
             :locals => { :action_search_path => @action_search_path } %>
                          
</div>

app/views/openstax/connect/users/_action_list.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<%
  users ||= []
%>

<% if list.num_columns > 0 %>
  <table class="list" width="100%">
    <% if list.has_headings? %>
      <tr>  
        <% for ii in 0..list.num_columns - 1 %>
          <th><%= list.get_heading(ii) %></th>
        <% end %>
      </tr>
    <% end %>

    <% if users.empty? %>
      <tr>
        <td colspan="<%= list.num_columns %>">No results</td>
      </tr>
    <% else %>
      <% users.all.each_with_index do |user, uu| %>
        <tr>
          <% for cc in 0..list.num_columns - 1 %>
            <% width = uu == 0 ? list.get_width(cc) : nil %>
            <td <%= "width=#{width}" if width %>><%= list.get_data(cc, user) %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
<% end %>

app/views/openstax/connect/users/_action_search.html.erb
<%# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
    License version 3 or later.  See the COPYRIGHT file for details. %>

<%
   # Clients of this partial must supply the following variables:
   #   action_search_path  
%>

<div id="action-search-errors"></div>

<%= lev_form_for :search, 
                 url: action_search_path, 
                 html: {id: 'action-search-form'},
                 remote: true do |f| %>

  Search for 
  <%= f.text_field :search_terms, style: 'width:300px' %> 
  in         
  <%= f.select :search_type, options_for_select(['Any', 'Name', 'Username']) %>

  <%= submit_tag 'Search' %>

<% end %>

<div id="action-search-results-list"></div>

app/views/openstax/connect/users/action_search.js.erb
<%= unless_errors errors_html_id: (errors_html_id ||= 'action-search-errors') do %>
  <% contents = render 'openstax/connect/users/action_list', 
                       users: users, 
                       list: list %>
  
  $("#action-search-results-list").html("<%= j(contents) %>");  
<% end %>